[assembly: AssemblyTitle("FreeLookInCars")]
[assembly: AssemblyDescription("Allows the player to look freely in cars")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("FreeLookInCars")]
[assembly: AssemblyCopyright("© 2018 Wulf Marius")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]

[assembly: AssemblyVersion("4.0.2.0")]
[assembly: AssemblyFileVersion("4.0.2.0")]
[assembly: MelonInfo(typeof(FreeLookInCars.FreeLookInCars), "FreeLookInCars", "4.0.2", "WulfMarius, zeobviouslyfakeacc, The Illusion")]
[assembly: MelonGame("Hinterland", "TheLongDark")]
